name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # ou a versão do Java que seu projeto usa

    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew  # Dá permissão de execução ao script gradlew

    - name: Build with Gradle
      run: ./gradlew clean build  # Agora deve funcionar com permissão de execução

    - name: Run Tests
      run: ./gradlew test
