name: Testando Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  exemplo:
    runs-on: ubuntu-latest

    steps:
      - name: Configurando repositório
        uses: actions/checkout@v2

      - name: Passo 1 - Exibindo mensagem
        run: echo "Ação 1: Iniciando o workflow no GitHub Actions"

      - name: Passo 2 - Exibindo outra mensagem
        run: echo "Ação 2: Tudo funcionando perfeitamente!"
